# This file will be regenerated by `mulle-match-to-cmake` via
# `mulle-sde reflect` and any edits will be lost.
#
# This file will be included by cmake/share/sources.cmake
#
if( MULLE_TRACE_INCLUDE)
   MESSAGE( STATUS "# Include \"${CMAKE_CURRENT_LIST_FILE}\"" )
endif()

#
# contents selected with patternfile ??-source--sources
#
set( SOURCES
src/MulleCommentedLocalizableStrings.m
src/NSMutableDictionary+MulleSingleOrMultiValueObjects.m
src/NSString+MulleCaseInsensitiveCompare.m
src/NSString+MulleEnumerateNSLocalizedStringParameters.m
src/NSString+MulleQuotedString.m
src/NSString+MulleValiantFile.m
src/NSTask+System.m
src/main.m
src/parser.m
)
