/*
 *   This file will be regenerated by `mulle-sourcetree-to-c --project-dialect objc` via
 *   `mulle-sde reflect` and any edits will be lost.
 *   Suppress generation of this file with:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_IMPORT_FILE DISABLE
 *
 *   To not let mulle-sourcetree-to-c generate any header files:
 *
 *      mulle-sde environment set MULLE_SOURCETREE_TO_C_RUN DISABLE
 *
 */

// You can tweak the following #import with these commands.
// (Use D06A323E-5FAB-4C08-B60B-2535111F0999 instead of Foundation if there are duplicate entries)
//    remove #import: : `mulle-sde dependency mark Foundation no-header`
//    rename:              `mulle-sde dependency|library set Foundation include whatever.h`
//    reorder:             `mulle-sde dependency move Foundation <up|down>`
//    toggle #import:     `mulle-sde dependency mark Foundation [no-]import`
//    toggle public:       `mulle-sde dependency mark Foundation [no-]public`
//    toggle optional:     `mulle-sde dependency mark Foundation [no-]require`
//    remove for platform: `mulle-sde dependency mark Foundation no-platform-<uname>`
//        (use `mulle-sourcetree-to-c --unames` to list known values)
#import <Foundation/Foundation.h>   // Foundation
